### ISSUE TITLE
Add/move LICENSE to root :)

### ISSUE THREAD

**Issue by talaviram** [Lyve1981/dsp56300#10]
I've found that the project LICENSE is within the source and isn't mentioned in the root README.md.
would be nice if it'll be in the root and also for github to pick it up.

**Comment by henryborchers** [comment]
I agree. LICENSE.md should be in the root. Not only does it make the important document easy to find, but github actually looks for a LICENSE.md in the root for the repo's metadata.

**Comment by Lyve1981** [comment]
fixed 👍
