### ISSUE TITLE
Need any help with your CMake build system?

### ISSUE THREAD

**Issue by henryborchers** [Lyve1981/dsp56300#6]
Are you taking PR for improving your cmake? I noticed that the current build system isn't as easy to consume the build targets and doesn't take advantage of the goodies of modern CMake.

**Comment by Lyve1981** [comment]
Of course, thanks in advance!

**Comment by henryborchers** [comment]
@Lyve1981 any objections to me creating a github actions to test and make sure cross platform compatibility before updating the cmakelists.txt?
